### ISSUE TITLE
Might give examples of how vim-textobj-sentence handles touted benefits

### ISSUE THREAD

**Issue by panozzaj** [reedes/vim-textobj-sentence#9]
Hi Reed, hope things are going well! I was reading through the documentation (working on previously referenced Vim book (finally)) and saw a couple of benefits that the README mentions that I'm not sure I fully understand. I could dig into the code, but figured it might be a case where it could be clearer to others as well.

Here are the relevant sections:

 - Support for sentences containing typographical characters, incl. quotes, em dash, etc.
 - Support for lightweight markup languages (markdown, e.g.)

I was not clear how having dashes would affect the sentence finding algorithm. Same with things like asterisks around words inside of sentences.

Thank you for your work on this plugin, it is quite useful for moving around and manipulating sentences!

**Comment by reedes** [comment]
I recall that markup (markdown, etc.) at the beginning (and end?) of sentences wasn't being handled correctly by the native sentence navigator. Some of the relevant regression tests: https://github.com/reedes/vim-textobj-sentence/blob/master/tests/select_markdown.vader

The native sentence navigator wasn't working properly with typographical (curly) quotes, which was a motivation to write the plugin. 

As far as em dashes, there must have been odd behavior, as I have three regression tests around fixing them: https://github.com/reedes/vim-textobj-sentence/blob/master/tests/select_general.vader#L81-L122

**Comment by panozzaj** [comment]
Ah, excellent! I didn't think to check the tests. Thanks for the quick reply!
